config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :photos, only: [:index, :new, :create]

  get    '/oauth/callback',   to: 'twitter#callback'
  get    'tweet',             to: 'twitter#tweet'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user

  default_scope -> { order(created_at: :desc) }
  
  validates :user_id, presence: true
  validates :title, presence: { message: 'を入力してください' }
  validates :image, presence: { message: 'を選択してください' }

  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  has_many :photos
  validates :uid, presence: true
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  
  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :logged_in_user

  def index
    @photos = current_user.photos
    @twitter_authorize_uri = twitter_authorize_uri
  end

  def new
    @photo = current_user.photos.build
  end

  def create
    @photo = Photo.new(photo_params)
    @photo.image.attach(params[:photo][:image])
    if @photo.save
      redirect_to photos_path
    else
      render :new
    end
  end

  private
    def photo_params
      params.require(:photo).permit(:user_id, :title, :image)
    end

    def twitter_authorize_uri
      host = Rails.configuration.settings[:twitter][:host]
      path = Rails.configuration.settings[:twitter][:authorize_path]
      params = {
        'response_type' => 'code',
        'client_id' => '28fa91cecc903483ef240c7e9d6607d267868a05f6c1b3f59e6ea1bd5eabb74f',
        'redirect_uri' => 'http://localhost:3000/oauth/callback',
        'scope' => '',
        'state' => ''
      }
      "#{host}#{path}?#{URI.encode_www_form(params)}"
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(user_id: params[:session][:user_id])
    @erros = []
    @erros << 'ユーザIDを入力してください' if params[:session][:user_id].empty?
    @erros << 'パスワードを入力してください' if params[:session][:password].empty?
    if user == nil || user.authenticate(params[:session][:password]) == false
      @erros << 'ユーザID、パスワードが一致するユーザが存在しません'
    end

    if @erros.present?
      render 'new'
    else
      log_in user
      redirect_to photos_path
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end

end

app/controllers/twitter_controller.rb
class TwitterController < ApplicationController
  before_action :logged_in_user

  require 'net/http'
  
  def callback
    host = Rails.configuration.settings[:twitter][:host]
    path = Rails.configuration.settings[:twitter][:token_request_path]
    uri = URI("#{host}#{path}")
    p = {
      'code' => params[:code],
      'client_id' => '28fa91cecc903483ef240c7e9d6607d267868a05f6c1b3f59e6ea1bd5eabb74f',
      'client_secret' => '6fda083d97114f7be097f99cedc28175b9dce9c825a876baa24c46a75db57be4',
      'redirect_uri' => 'http://localhost:3000/oauth/callback',
      'grant_type' => 'authorization_code'
    }
    res = Net::HTTP.post_form(uri, p)
    if res.is_a?(Net::HTTPSuccess)
      body = JSON.parse(res.body)
      current_user.twitter_access_token = body['access_token']
      current_user.save
      redirect_to photos_path
    end
  end

  def tweet
    host = Rails.configuration.settings[:twitter][:host]
    path = Rails.configuration.settings[:twitter][:tweets_path]
    uri = URI("#{host}#{path}")
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = uri.scheme === "https"
    body = {
      'text' => params[:title],
      'url' => params[:image_url],
    }
    headers = {
      'Content-Type' => 'application/json',
      'Authorization' => "Bearer #{current_user.twitter_access_token}"
    }
    res = http.post(uri.path, body.to_json, headers)
    redirect_to photos_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(uid: params[:session][:uid])
    @erros = []
    @erros << 'ユーザIDを入力してください' if params[:session][:uid].empty?
    @erros << 'パスワードを入力してください' if params[:session][:password].empty?
    if user == nil || user.authenticate(params[:session][:password]) == false
      @erros << 'ユーザID、パスワードが一致するユーザが存在しません'
    end

    if @erros.present?
      render 'new'
    else
      log_in user
      redirect_to photos_path
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | PhotoApp
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = yield

app/views/photos/_form.html.slim
= form_for @photo do |f|
  - if @photo.errors.any?
    ul.errors
      - @photo.errors.full_messages.each do |message|
        li = message
  p
    = f.label :title, 'タイトル'
    = f.text_field :title
  p
    = f.label :image, '画像ファイル'
    = f.file_field :image
  = f.hidden_field :user_id
  .actions = f.submit 'アップロード'
 

app/views/photos/index.html.slim
= link_to 'ログアウト', logout_path, method: :delete
h1 写真一覧
.
  p = link_to '写真アップロード', new_photo_path
  p = link_to 'MyTestApp', @twitter_authorize_uri
.container
  - @photos.each do |photo|
    .item
      = photo.title
      . = image_tag photo.image, class:'image' if photo.image.attached?
      - if current_user.twitter_access_token.present? && photo.image.attached?
        - image_url = photo.image
        . 
          = link_to tweet_path(title: photo.title, image_url: "http://localhost:3000#{url_for(photo.image)}" ) do
           = button_tag 'ツイートする'

app/views/photos/new.html.slim
h1 写真アップロード
== render 'form'
= link_to 'キャンセル', photos_path